<?php
/**
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause
 * @copyright Copyright (c) 2015 Julien Guittard (http://julienguittard.com)
 */

namespace Zoho\Subscriptions\Entity;

/**
 * Class ContactPerson
 *
 * @package Zoho\Subscriptions\Entity
 */
class ContactPerson implements EntityInterface
{
    /**
     * Unique ID generated by the server.This can be used as an identifier.
     *
     * @var string
     */
    protected $contactpersonId;

    /**
     * First name of the contact person.
     *
     * @var string
     */
    protected $firstName;

    /**
     * Last name of the contact person.
     *
     * @var string
     */
    protected $lastName;

    /**
     * Email ID of the contact person to whom notifications regarding the subscription needs to be sent.
     *
     * @var string
     */
    protected $email;

    /**
     * Landline or fixed line number of the contact person.
     *
     * @var string
     */
    protected $phone;

    /**
     * Mobile number of the contact person.
     *
     * @var string
     */
    protected $mobile;

    /**
     * Customer ID of the customer the contact person is associated with.
     *
     * @var string
     */
    protected $customerId;

    /**
     * Get the contact person ID
     *
     * @return string
     */
    public function getContactpersonId()
    {
        return $this->contactpersonId;
    }

    /**
     * Set the contact person ID
     *
     * @param string $contactpersonId
     * @return ContactPerson
     */
    public function setContactpersonId($contactpersonId)
    {
        $this->contactpersonId = $contactpersonId;
        return $this;
    }

    /**
     * Get the first name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set the first name
     *
     * @param string $firstName
     * @return ContactPerson
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * Get the last name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set the last name
     *
     * @param string $lastName
     * @return ContactPerson
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
        return $this;
    }

    /**
     * Get the email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the email
     *
     * @param string $email
     * @return ContactPerson
     */
    public function setEmail($email)
    {
        $this->email = $email;
        return $this;
    }

    /**
     * Get the phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set the phone
     *
     * @param string $phone
     * @return ContactPerson
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
        return $this;
    }

    /**
     * Get the mobile
     *
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Set the mobile
     *
     * @param string $mobile
     * @return ContactPerson
     */
    public function setMobile($mobile)
    {
        $this->mobile = $mobile;
        return $this;
    }

    /**
     * Get the customer ID
     *
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customerId;
    }

    /**
     * Set the customer ID
     *
     * @param string $customerId
     * @return ContactPerson
     */
    public function setCustomerId($customerId)
    {
        $this->customerId = $customerId;
        return $this;
    }
}
