<?php
/**
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause
 * @copyright Copyright (c) 2015 Julien Guittard (http://julienguittard.com)
 */

namespace Zoho\Subscriptions\Entity;

use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterAwareTrait;

/**
 * Class Product
 *
 * @package Zoho\Subscriptions\Entity
 */
class Product implements InputFilterAwareInterface
{
    use InputFilterAwareTrait;
    use TimestampableTrait;
    use StatusTrait;

    /**
     * Unique ID generated by the server for the product.
     *
     * @var string
     */
    protected $productId;

    /**
     * Name of your choice to be displayed in the interface.
     *
     * @var string
     */
    protected $name;

    /**
     * Short description regarding the product.
     *
     * @var string
     */
    protected $description;

    /**
     * The email IDs to which notifications related to the product need to be sent.
     * (Use comma separation for multiple email-ids)
     *
     * @var string
     */
    protected $emailIds;

    /**
     * The URL to which customers should be redirected to once they subscribe to the product.
     * @var string
     */
    protected $redirectUrl;

    /**
     * @return string
     */
    public function getProductId()
    {
        return $this->productId;
    }

    /**
     * @param string $productId
     * @return Product
     */
    public function setProductId($productId)
    {
        $this->productId = $productId;
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Product
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Product
     */
    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return string
     */
    public function getEmailIds()
    {
        return $this->emailIds;
    }

    /**
     * @param string $emailIds
     * @return Product
     */
    public function setEmailIds($emailIds)
    {
        $this->emailIds = $emailIds;
        return $this;
    }

    /**
     * @return string
     */
    public function getRedirectUrl()
    {
        return $this->redirectUrl;
    }

    /**
     * @param string $redirectUrl
     * @return Product
     */
    public function setRedirectUrl($redirectUrl)
    {
        $this->redirectUrl = $redirectUrl;
        return $this;
    }
}
